/**
 * Validation Agent
 * Verifies that the executed node produced the expected output schema and required fields.
 */
class ValidationAgent {
  constructor() {
    this.name = 'validation';
  }

  /**
   * Validate node execution output
   * @param {Object} node - The node configuration
   * @param {Object} output - The output generated by the Execution Agent
   * @returns {Object} { isValid: Boolean, errors: Array<String>, missingFields: Array<String> }
   */
  async validate(node, output) {
    const requiredFields = node.data?.requiredFields || [];
    const errors = [];
    const missingFields = [];

    if (!output || typeof output !== 'object') {
      return {
        isValid: false,
        errors: ['Execution output is empty or not an object.'],
        missingFields: requiredFields,
      };
    }

    // Check specific required fields if defined in node config
    for (const field of requiredFields) {
      // Check in output, or in node.data.params
      const inOutput = output[field] !== undefined && output[field] !== null && output[field] !== '';
      const inParams = node.data?.params?.[field] !== undefined && node.data?.params?.[field] !== '';

      if (!inOutput && !inParams) {
        missingFields.push(field);
        errors.push(`Missing required field: '${field}'`);
      }
    }

    // General output sanity checks
    if (output.error) {
      errors.push(`Node reported internal error: ${output.error}`);
    }

    const isValid = errors.length === 0;

    return {
      isValid,
      errors,
      missingFields,
      validationTime: new Date().toISOString(),
      nodeId: node.id,
    };
  }
}

module.exports = new ValidationAgent();
